name: Clojure

on:
  push:
    branches: [ master ]
    tags:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache deps
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build uberjar
      run: clj -A:uberjar
  build_and_publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker build --tag well_feedit:$GITHUB_SHA .
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u darksoy --password-stdin
    - name: Push image
      run: |
        IMAGE_NAME=${GITHUB_REPOSITORY##*/}
        IMAGE_ID=darksoy/$IMAGE_NAME

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=${GITHUB_REF##*/}
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo IMAGE_ID=$IMAGE_ID
        docker tag well_feedit:$GITHUB_SHA $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
